<Text>{congressman.date_of_birth}</Text>
<Text>{congressman.district}</Text>
<Text>{congressman.facebook_account}</Text>
<Text>{congressman.fax}</Text>
<Text>{congressman.first_name}</Text>
<Text>{congressman.gender}</Text>
<Text>{congressman.geoid}</Text>
<Text>{congressman.google_entity_id}</Text>
<Text>{congressman.govtrack_id}</Text>
<Text>{congressman.last_name}</Text>
<Text>{congressman.last_updated}</Text>
<Text>{congressman.leadership_role}</Text>
<Text>{congressman.middle_name}</Text>
<Text>{congressman.next_election}</Text>
<Text>{congressman.office}</Text>
<Text>{congressman.party}</Text>
<Text>{congressman.phone}</Text>
<Text>{congressman.rss_url}</Text>
<Text>{congressman.seniority}</Text>
<Text>{congressman.short_title}</Text>
<Text>{congressman.state}</Text>
<Text>{congressman.suffix}</Text>
<Text>{congressman.title}</Text>
<Text>{congressman.total_present}</Text>
<Text>{congressman.total_votes}</Text>
<Text>{congressman.twitter_account}</Text>
<Text>{congressman.url}</Text>
<Text>{congressman.votes_against_party_pct}</Text>
<Text>{congressman.votes_with_party_pct}</Text>
<Text>{congressman.votesmart_id}</Text>
<Text>{congressman.youtube_account: